package com.jayam.impactapp.common;

public enum ServiceMethods {
    LOGIN, INTIALPARAMS, GETDATES, REGULARDEMANDS, UPLOADDATA, ODDEMANDS, CHANGEPASSWORD, VERIFYDOWNLOAD, UPLOADIMAGE, ADVANCEDEMANDS, NPSDEMANDS, FTODREASONS, LUCDEMANDS, UPLOADLUCDATA
}
